[build]
rustflags = [
    "-W", "missing_docs",
]
incremental = true

[target.x86_64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=10.9",
]

[target.aarch64-apple-darwin]
rustflags = [
    "-W", "missing_docs",
    "-C", "link-arg=-mmacosx-version-min=11.0",
]

[profile.release]
strip = true

[env]
LLVM_SYS_130_PREFIX = { value = "./llvm_build/", relative = true, force = true }

[tools.clippy]
warn = [
    "missing_docs_in_private_items",
]
